### ISSUE TITLE
NSW Workshop James's assigment

### ISSUE THREAD

**Issue by jsondune** [jsondune/dohmis#7]
- [x] ร้อยละของวัยทำงานอายุ 30-44 ปี มีค่าดัชนีมวลกายปกติ
[Q3-15-s_kpi_bmi-ampur.txt](https://github.com/jsondune/dohmis/files/1224598/Q3-15-s_kpi_bmi-ampur.txt)

- [x] OHSP ร้อยละของผู้สูงอายุ ที่มีฟันแท้ใช้งานได้ไม่น้อยกว่า 20 ซี่
[Q3-16-s_kpi_dental40-ampur.txt](https://github.com/jsondune/dohmis/files/1224615/Q3-16-s_kpi_dental40-ampur.txt)

**Comment by jsondune** [comment]
โอ๊ต 
- [ ] ร้อยละของเด็กอายุ 0 – 5 ปี มีพัฒนาการสมวัย
- [ ] ผลการดำเนินการการคัดกรองพัฒนาการเด็กตามกลุ่มอายุ specialpp

**Comment by jsondune** [comment]
นุ
- [ ] ร้อยละของการตั้งครรภ์ซ้ำในหญิงอายุน้อยกว่า 20 ปี
- [ ] ร้อยละของหญิงอายุน้อยกว่า 20 ปี ที่ได้รับบริการคุมกำเนิดด้วยวิธีสมัยใหม่ (Modern Methods) หลังคลอดหรือหลังแท้ง
- [ ] ร้อยละของหญิงไทยอายุน้อยกว่า 20 ปี หลังคลอดหรือหลังแท้งที่คุมกำเนิดได้รับการคุมกำเนิดด้วยวิธีกึ่งถาวร (ยาฝังคุมกำเนิด/ห่วงอนามัย)

**Comment by jsondune** [comment]
กอล์ฟ
- [ ] ร้อยละของทารกแรกเกิดน้ำหนักน้อยกว่า 2,500 กรัม
- [ ] ร้อยละของเด็กแรกเกิด - ต่ำกว่า 6 เดือน กินนมแม่อย่างเดียว

**Comment by jsondune** [comment]
ปอม
- [ ] ข้อมูลด้านโภชนาการ เด็กอายุน้อยกว่า 6 ปี
- [ ] ข้อมูลด้านโภชนาการ ประชากรอายุ 15 ปีขึ้นไป
- [ ] ข้อมูลด้านโภชนาการ เด็กวัยเรียน อายุ 6-18 ปี
- [ ] ภาวะโลหิตจางในหญิงตั้งครรภ์

**Comment by jsondune** [comment]
- [ ] ร้อยละของวัยทำงานอายุ 30-44 ปี มีค่าดัชนีมวลกายปกติ
- [ ] OHSP ร้อยละของผู้สูงอายุ ที่มีฟันแท้ใช้งานได้ไม่น้อยกว่า 20 ซี่

**Comment by jamespakorn** [comment]
Successful
